- name: yum install base
  yum:
    name: {{ item }}
    state: present
  with_items:
    - rsync
    - vim
    - bash-completion
    - lrzsz
    - net-tools
    - tcpdump
    - telnet
    - chrony
    - sysstat
    - wget
  tags: yum_install_base
